#!/usr/bin/env bash

# Script to display information about subdomains

# Function to display subdomain information
display_subdomain_info() {
    sub_domain=$1
    domain=$2
    record_type=$(dig $sub_domain.$domain | awk '/IN[[:space:]]+A/{print $4}')
    destination=$(dig $sub_domain.$domain | awk '/IN[[:space:]]+A/{print $5}')
    echo "The subdomain $sub_domain is a $record_type record and points to $destination"
}

# Main function
main() {
    domain=$1
    sub_domain=$2

    if [ -z "$sub_domain" ]; then
        sub_domains=("www" "lb-01" "web-01" "web-02")
        for sub in "${sub_domains[@]}"; do
            display_subdomain_info $sub $domain
        done
    else
        display_subdomain_info $sub_domain $domain
    fi
}

# Execute main function with provided arguments
main "$@"
